-- Estrutura do Pulso. SQL portável entre H2 (desenvolvimento e testes) e PostgreSQL (produção).

CREATE TABLE unidade (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(80)  NOT NULL,
    cidade        VARCHAR(60)  NOT NULL,
    uf            VARCHAR(2)   NOT NULL,
    capacidade    INTEGER      NOT NULL,
    criado_em     TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_unidade_nome UNIQUE (nome)
);

CREATE TABLE modalidade (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome   VARCHAR(40) NOT NULL,
    icone  VARCHAR(8)  NOT NULL,
    CONSTRAINT uk_modalidade_nome UNIQUE (nome)
);

CREATE TABLE plano (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(40)   NOT NULL,
    valor_mensal   NUMERIC(10,2) NOT NULL,
    duracao_meses  INTEGER       NOT NULL,
    multi_unidade  BOOLEAN       NOT NULL,
    CONSTRAINT uk_plano_nome UNIQUE (nome)
);

CREATE TABLE plano_modalidade (
    plano_id       BIGINT NOT NULL,
    modalidade_id  BIGINT NOT NULL,
    PRIMARY KEY (plano_id, modalidade_id),
    CONSTRAINT fk_pm_plano FOREIGN KEY (plano_id) REFERENCES plano (id),
    CONSTRAINT fk_pm_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade (id)
);

CREATE TABLE instrutor (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(80) NOT NULL,
    unidade_id  BIGINT      NOT NULL,
    CONSTRAINT fk_instrutor_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id)
);

CREATE TABLE aluno (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(120) NOT NULL,
    cpf           VARCHAR(14)  NOT NULL,
    email         VARCHAR(120) NOT NULL,
    nascimento    DATE         NOT NULL,
    bairro        VARCHAR(80)  NOT NULL,
    cidade        VARCHAR(60)  NOT NULL,
    uf            VARCHAR(2)   NOT NULL,
    unidade_id    BIGINT       NOT NULL,
    criado_em     TIMESTAMP(6) NOT NULL,
    atualizado_em TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_aluno_cpf UNIQUE (cpf),
    CONSTRAINT uk_aluno_email UNIQUE (email),
    CONSTRAINT fk_aluno_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id)
);

CREATE TABLE matricula (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id             BIGINT       NOT NULL,
    plano_id             BIGINT       NOT NULL,
    inicio               DATE         NOT NULL,
    fim                  DATE,
    status               VARCHAR(10)  NOT NULL,
    motivo_cancelamento  VARCHAR(80),
    criado_em            TIMESTAMP(6) NOT NULL,
    atualizado_em        TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_matricula_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id),
    CONSTRAINT fk_matricula_plano FOREIGN KEY (plano_id) REFERENCES plano (id)
);
CREATE INDEX ix_matricula_aluno ON matricula (aluno_id);
CREATE INDEX ix_matricula_status ON matricula (status);

-- Herança SINGLE_TABLE: Pix, cartão e boleto na mesma tabela, distinguidos pela coluna "forma".
CREATE TABLE pagamento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forma            VARCHAR(10)   NOT NULL,
    valor            NUMERIC(10,2) NOT NULL,
    pago_em          TIMESTAMP(6)  NOT NULL,
    txid             VARCHAR(35),
    final_cartao     VARCHAR(4),
    linha_digitavel  VARCHAR(60)
);

CREATE TABLE mensalidade (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula_id  BIGINT        NOT NULL,
    competencia   DATE          NOT NULL,
    valor         NUMERIC(10,2) NOT NULL,
    vencimento    DATE          NOT NULL,
    pagamento_id  BIGINT,
    criado_em     TIMESTAMP(6)  NOT NULL,
    atualizado_em TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_mensalidade_competencia UNIQUE (matricula_id, competencia),
    CONSTRAINT uk_mensalidade_pagamento UNIQUE (pagamento_id),
    CONSTRAINT fk_mensalidade_matricula FOREIGN KEY (matricula_id) REFERENCES matricula (id),
    CONSTRAINT fk_mensalidade_pagamento FOREIGN KEY (pagamento_id) REFERENCES pagamento (id)
);
CREATE INDEX ix_mensalidade_vencimento ON mensalidade (vencimento);

CREATE TABLE avaliacao_fisica (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id            BIGINT        NOT NULL,
    data                DATE          NOT NULL,
    peso                NUMERIC(5,2)  NOT NULL,
    altura              NUMERIC(3,2)  NOT NULL,
    percentual_gordura  NUMERIC(4,1),
    cintura_cm          NUMERIC(5,1),
    criado_em           TIMESTAMP(6)  NOT NULL,
    atualizado_em       TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_avaliacao_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id)
);
CREATE INDEX ix_avaliacao_aluno ON avaliacao_fisica (aluno_id, data);

CREATE TABLE aula (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modalidade_id BIGINT       NOT NULL,
    unidade_id    BIGINT       NOT NULL,
    instrutor_id  BIGINT       NOT NULL,
    inicio        TIMESTAMP(6) NOT NULL,
    duracao_min   INTEGER      NOT NULL,
    vagas         INTEGER      NOT NULL,
    versao        BIGINT       NOT NULL,
    CONSTRAINT fk_aula_modalidade FOREIGN KEY (modalidade_id) REFERENCES modalidade (id),
    CONSTRAINT fk_aula_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id),
    CONSTRAINT fk_aula_instrutor FOREIGN KEY (instrutor_id) REFERENCES instrutor (id)
);
CREATE INDEX ix_aula_inicio ON aula (unidade_id, inicio);

CREATE TABLE reserva (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aula_id    BIGINT       NOT NULL,
    aluno_id   BIGINT       NOT NULL,
    status     VARCHAR(10)  NOT NULL,
    criada_em  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_reserva_aula_aluno UNIQUE (aula_id, aluno_id),
    CONSTRAINT fk_reserva_aula FOREIGN KEY (aula_id) REFERENCES aula (id),
    CONSTRAINT fk_reserva_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id)
);

CREATE TABLE acesso (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id    BIGINT       NOT NULL,
    unidade_id  BIGINT       NOT NULL,
    entrada     TIMESTAMP(6) NOT NULL,
    saida       TIMESTAMP(6),
    CONSTRAINT fk_acesso_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id),
    CONSTRAINT fk_acesso_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id)
);
CREATE INDEX ix_acesso_unidade ON acesso (unidade_id, entrada);
CREATE INDEX ix_acesso_aluno ON acesso (aluno_id, entrada);
