-- Contatos de retenção: o que a equipe fez depois de o Pulso avisar que um aluno estava em risco.
CREATE TABLE contato (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_id       BIGINT       NOT NULL,
    canal          VARCHAR(12)  NOT NULL,
    resultado      VARCHAR(20)  NOT NULL,
    observacao     VARCHAR(200),
    feito_em       TIMESTAMP(6) NOT NULL,
    risco_na_epoca INTEGER      NOT NULL,
    CONSTRAINT fk_contato_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id)
);
CREATE INDEX ix_contato_aluno ON contato (aluno_id, feito_em);
CREATE INDEX ix_contato_feito_em ON contato (feito_em);
