-- Contas de acesso. Gerente e recepção ficam presos a uma unidade; o aluno, ao próprio cadastro.
CREATE TABLE usuario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login             VARCHAR(120) NOT NULL,
    nome              VARCHAR(120) NOT NULL,
    senha_hash        VARCHAR(100) NOT NULL,
    perfil            VARCHAR(12)  NOT NULL,
    unidade_id        BIGINT,
    aluno_id          BIGINT,
    tentativas_falhas INTEGER      NOT NULL,
    bloqueado_ate     TIMESTAMP(6),
    ativo             BOOLEAN      NOT NULL,
    criado_em         TIMESTAMP(6) NOT NULL,
    atualizado_em     TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_usuario_login UNIQUE (login),
    CONSTRAINT fk_usuario_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id),
    CONSTRAINT fk_usuario_aluno FOREIGN KEY (aluno_id) REFERENCES aluno (id)
);
